name: money_hustle
description: "A base app"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8

  flutter_keyboard_visibility: 6.0.0
  flutter_screenutil: 5.9.1
  collection: 1.19.1
  flutter_svg: 2.2.3
  lottie: 3.3.2
  go_router: 16.2.1

  smooth_page_indicator: 1.2.1
  intl: any
  shared_preferences: 2.5.3
  in_app_review: 2.0.11
  provider: 6.1.5+1
  uuid: 4.5.2
  package_info_plus: 9.0.0
  share_plus: 12.0.1
  path_provider: 2.1.5
  apphud_helper:
    git:
      url: https://github.com/AppEmpireSwift/apphud_helper.git
      ref: 0.6.1
  http: 1.6.0
  url_launcher: 6.3.2
  device_preview_plus: 2.5.5
  dart_unused_files: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  flutter_gen_runner: ^5.12.0

  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/vectors/
    - assets/lottie/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/premium/
